"""RED tests for the certificate utilities under ``myinvois.ubl.signing``.

These tests pin the *PHP-emitted wire forms* for every byte-sequence the
signature builder needs from the signing cert:

* PEM-stripped raw base64 content (the bytes that go into
  ``<ds:X509Certificate>...</ds:X509Certificate>`` / JSON ``X509Certificate``
  keyed ``_`` field) — matches the PHP ``AbstractDocumentBuilder::
  getRawContent()`` algorithm (no separators between base64 chunks).
* Issuer-name string (``urldecode(http_build_query(issuer_dict, "", ", "))``
  with the ``CN/E/OU/O/C`` reorder quirk; PHP ``openssl_x509_parse`` already
  returns ``emailAddress`` rather than ``E`` as override key — the loop is
  effectively ``[CN, OU, O, C]`` for our test cert).
* Serial-number string (``0x{UPPER_HEX}``) — matches PHP ``openssl_x509_parse``
  verbatim.
* Cert digest (``base64(SHA256(cert_der))``) —
  matches the ``<ds:DigestValue>`` inside ``<xades:CertDigest>``.

All four are verified byte-for-byte equal to the values embedded in the
PHP-generated fixtures:

* ``golden_invoice_signed.xml`` / ``golden_invoice_signed.json`` —
  generated by ``scripts/gen_signed_golden.php`` (deterministic
  SigningTime = ``2024-01-15T10:00:00Z``).

Until the module is implemented these tests are marked ``xfail(strict=True)``.
Setting ``EXPECT_IMPLEMENTED = True`` at the top flips them to required so
the implementation effort has a clear green target.
"""

from __future__ import annotations

from pathlib import Path

import pytest

# Flip to True once myinvois.ubl.signing._cert is implemented.
EXPECT_IMPLEMENTED = True

_XFAIL_REASON = (
    "myinvois.ubl.signing._cert helpers not yet implemented (Phase 4.4). "
    "Set EXPECT_IMPLEMENTED=True at the top of this file once green."
)


def _maybe_xfail(func):
    if EXPECT_IMPLEMENTED:
        return func
    return pytest.mark.xfail(reason=_XFAIL_REASON, strict=True)(func)


# ---------------------------------------------------------------------------
# Fixture paths.
# ---------------------------------------------------------------------------

_CERT_PEM = Path(__file__).resolve().parent.parent / "fixtures" / "cert" / "dummy_signing_cert.pem"
_KEY_PEM = Path(__file__).resolve().parent.parent / "fixtures" / "cert" / "dummy_signing_key.pem"
_XML_FIXTURE = Path(__file__).resolve().parent.parent / "fixtures" / "golden_invoice_signed.xml"
_JSON_FIXTURE = Path(__file__).resolve().parent.parent / "fixtures" / "golden_invoice_signed.json"


# Expected wire bytes (extracted from the PHP-generated fixtures; see AGENTS.md).
_EXPECTED_ISSUER_NAME = (
    "emailAddress=test@example.com, CN=Test LHDN Signing, "
    "OU=MyInvoice Unit, O=Test Org, C=MY"
)
_EXPECTED_SERIAL_NUMBER = "0x10D75D74EB922AEE2774FACA060AC339BE6AC425"
_EXPECTED_CERT_DIGEST_B64 = "UlhmSPmya4BK8Vd+VPdKdOxUAiLXC4F1uc1EB+NlaRM="


# ---------------------------------------------------------------------------
# Import helper: keeps the file importable before the impl lands.
# ---------------------------------------------------------------------------

def _import_cert_module():
    if EXPECT_IMPLEMENTED:
        from myinvois.ubl.signing import _cert
        return _cert
    pytest.skip("myinvois.ubl.signing._cert not yet importable")


# ---------------------------------------------------------------------------
# PEM raw content (the ``<ds:X509Certificate>`` value) — mirrors PHP
# ``getRawContent``: strip BEGIN / END lines, drop trailing blank lines, then
# ``"".join`` remaining chunks (no ``\n`` separators).
# ---------------------------------------------------------------------------

def _expected_cert_raw_from_pem() -> str:
    """Replicate PHP getRawContent on the fixture cert PEM."""
    pem = _CERT_PEM.read_text(encoding="utf-8")
    arr = pem.replace("\r", "").split("\n")
    del arr[0]  # -----BEGIN CERTIFICATE-----
    while arr and arr[-1] == "":
        arr.pop()
    if arr:
        arr.pop()  # -----END CERTIFICATE-----
    return "".join(arr)


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

class TestCertPemRawContent:
    @_maybe_xfail
    def test_returns_base64_chunks_without_separators(self) -> None:
        cert = _import_cert_module()
        pem = _CERT_PEM.read_text(encoding="utf-8")
        out = cert.cert_pem_raw_content(pem)
        assert out == _expected_cert_raw_from_pem()

    @_maybe_xfail
    def test_matches_fixture_signed_xml_certificate_value(self) -> None:
        """The same raw bytes appear in the golden XML ``<ds:X509Certificate>`` element."""
        cert = _import_cert_module()
        pem = _CERT_PEM.read_text(encoding="utf-8")
        out = cert.cert_pem_raw_content(pem)
        xml = _XML_FIXTURE.read_text(encoding="utf-8")
        assert f"<ds:X509Certificate>{out}</ds:X509Certificate>" in xml


class TestIssuerNameString:
    @_maybe_xfail
    def test_returns_php_canonical_form(self) -> None:
        cert = _import_cert_module()
        cert_obj = cert.load_x509(_CERT_PEM.read_bytes())
        assert cert.issuer_name_string(cert_obj) == _EXPECTED_ISSUER_NAME

    @_maybe_xfail
    def test_matches_fixture_xml_x509_issuer_name(self) -> None:
        import re

        cert = _import_cert_module()
        cert_obj = cert.load_x509(_CERT_PEM.read_bytes())
        issuer = cert.issuer_name_string(cert_obj)
        xml = _XML_FIXTURE.read_text(encoding="utf-8")
        # The XML uses ``<ds:X509IssuerName xmlns:ds="...">{issuer}</...>``
        # (the xmlns prefix is injected by ``replaceCommonAttributes``).
        assert re.search(
            fr"<ds:X509IssuerName[^>]*>{re.escape(issuer)}</ds:X509IssuerName>",
            xml,
        )


class TestSerialNumberString:
    @_maybe_xfail
    def test_returns_php_canonical_form(self) -> None:
        cert = _import_cert_module()
        cert_obj = cert.load_x509(_CERT_PEM.read_bytes())
        assert cert.serial_number_string(cert_obj) == _EXPECTED_SERIAL_NUMBER

    @_maybe_xfail
    def test_matches_fixture_xml_x509_serial_number(self) -> None:
        import re

        cert = _import_cert_module()
        cert_obj = cert.load_x509(_CERT_PEM.read_bytes())
        s = cert.serial_number_string(cert_obj)
        xml = _XML_FIXTURE.read_text(encoding="utf-8")
        assert re.search(
            fr"<ds:X509SerialNumber[^>]*>{re.escape(s)}</ds:X509SerialNumber>",
            xml,
        )


class TestCertDigestB64:
    @_maybe_xfail
    def test_returns_sha256_of_cert_der(self) -> None:
        cert = _import_cert_module()
        cert_obj = cert.load_x509(_CERT_PEM.read_bytes())
        assert cert.cert_digest_b64(cert_obj) == _EXPECTED_CERT_DIGEST_B64

    @_maybe_xfail
    def test_matches_fixture_xml_cert_digest_value(self) -> None:
        """The same digest appears in the golden XML ``<ds:DigestValue>`` inside
        ``<xades:CertDigest>``."""
        import re

        cert = _import_cert_module()
        cert_obj = cert.load_x509(_CERT_PEM.read_bytes())
        d = cert.cert_digest_b64(cert_obj)
        xml = _XML_FIXTURE.read_text(encoding="utf-8")
        assert re.search(
            fr"<ds:DigestValue[^>]*>{re.escape(d)}</ds:DigestValue>", xml
        )
