"""RED tests for ``XmlEnvelopeBuilder``.

These tests are the outer verification ring of Phase 3c (XML half). The
canonical reference output was generated by running
the reference implementation's ``XmlDocumentBuilder::build()`` on the same
invoice materialised by ``_sample_invoice()`` (mirrored field-for-field).
The resulting bytes are
pinned at ``tests/fixtures/golden_invoice_unsigned.xml`` (md5-checked
against the reference output during fixture population).

Until ``XmlEnvelopeBuilder.build_xml()`` is green (Phase 3c-XML Step 3),
every test in this file should be marked ``xfail`` to keep the rest of
the suite green, then unmarked once the implementation lands. Switching
``EXPECT_IMPLEMENTED`` to ``True`` flips all of them to required.

Note: the reference XmlDocumentBuilder finishes with C14N (canonical
XML 1.1) and strips the XML declaration. lxml matches this when
``etree.tostring(method='c14n', exclusive=True, with_comments=False)``
is called on a freshly-parsed tree — same code path Phase 4's signature
digest will use.
"""

from __future__ import annotations

import pytest

# Flip to True when the XmlEnvelopeBuilder implementation lands.
EXPECT_IMPLEMENTED = True

_XFAIL_REASON = (
    "XmlEnvelopeBuilder not yet implemented (Phase 3c-XML Step 3). "
    "Set EXPECT_IMPLEMENTED=True at the top of this file once green."
)


def _maybe_xfail(func):
    """Mark every RED test as xfail until the implementation lands."""
    if EXPECT_IMPLEMENTED:
        return func
    return pytest.mark.xfail(reason=_XFAIL_REASON, strict=True)(func)


# ---------------------------------------------------------------------------
# Fixture reuse — sample invoice is the same shape used by the JSON builder.
# ---------------------------------------------------------------------------

import sys  # noqa: E402

sys.path.insert(0, "tests/unit")
import test_envelope_builder as _json_fixture  # noqa: E402

_sample_invoice = _json_fixture._sample_invoice


# ---------------------------------------------------------------------------
# Lazy imports so importing this module doesn't blow up before the impl exists.
# ---------------------------------------------------------------------------


def _builder():
    from myinvois.ubl.builders import XmlEnvelopeBuilder

    return XmlEnvelopeBuilder(_sample_invoice())


def _golden_xml() -> str:
    from pathlib import Path

    p = Path(__file__).resolve().parent.parent / "fixtures" / "golden_invoice_unsigned.xml"
    return p.read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# 1. Outer envelope + namespaces
# ---------------------------------------------------------------------------


class TestXmlEnvelopeShape:
    @_maybe_xfail
    def test_build_xml_returns_str(self) -> None:
        assert isinstance(_builder().build_xml(), str)

    @_maybe_xfail
    def test_root_element_is_invoice_with_default_namespace(self) -> None:
        out = _builder().build_xml()
        # Canonical with-namespace ordering: xmlns (default) first, then
        # xmlns:cac, xmlns:cbc, xmlns:ext alphabetical by prefix.
        assert out.startswith(
            '<Invoice xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2" '
            'xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" '
            'xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2" '
            'xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2">'
        )

    @_maybe_xfail
    def test_output_has_no_xml_declaration(self) -> None:
        s = _builder().build_xml()
        assert not s.startswith("<?xml")
        assert "<?xml" not in s

    @_maybe_xfail
    def test_output_has_no_indentation_or_whitespace_between_elements(self) -> None:
        # C14N-1.1 strips inter-element whitespace. Only text content retains
        # spaces (e.g. "Lot 66, Bangunan Merdeka").
        s = _builder().build_xml()
        # No newlines, tabs, or carriage returns anywhere.
        assert "\n" not in s and "\t" not in s and "\r" not in s
        # No `> <` between adjacent elements (would indicate whitespace text).
        assert "> <" not in s

    @_maybe_xfail
    def test_top_level_invoice_closes_at_end(self) -> None:
        s = _builder().build_xml()
        assert s.endswith("</Invoice>")


# ---------------------------------------------------------------------------
# 2. Number formatting (XML differs from JSON: 2dp fixed, trailing zeros kept)
# ---------------------------------------------------------------------------


class TestXmlMoneyRendering:
    @_maybe_xfail
    def test_amount_with_two_dp_keeps_trailing_zero(self) -> None:
        s = _builder().build_xml()
        assert ">1436.50</cbc:LineExtensionAmount>" in s
        assert ">1436.50</cbc:TaxExclusiveAmount>" in s

    @_maybe_xfail
    def test_integer_amount_becomes_dot_zero_zero(self) -> None:
        s = _builder().build_xml()
        assert ">17.00</cbc:PriceAmount>" in s
        assert ">100.00</cbc:Amount>" in s

    @_maybe_xfail
    def test_sub_one_amount_preserves_leading_zero(self) -> None:
        s = _builder().build_xml()
        assert ">0.30</cbc:PayableRoundingAmount>" in s

    @_maybe_xfail
    def test_quantity_emits_as_2dp_fixed_with_unit_code_attr(self) -> None:
        s = _builder().build_xml()
        assert '<cbc:InvoicedQuantity unitCode="C62">1.00</cbc:InvoicedQuantity>' in s

    @_maybe_xfail
    def test_multiplier_factor_numeric_uses_2dp(self) -> None:
        s = _builder().build_xml()
        assert ">0.15</cbc:MultiplierFactorNumeric>" in s
        assert ">0.10</cbc:MultiplierFactorNumeric>" in s

    @_maybe_xfail
    def test_percent_emits_as_2dp_fixed(self) -> None:
        s = _builder().build_xml()
        assert ">10.00</cbc:Percent>" in s


# ---------------------------------------------------------------------------
# 3. Element prefixing (cbc vs cac) per UBL 2.1 schema
# ---------------------------------------------------------------------------


class TestElementPrefixing:
    @_maybe_xfail
    def test_root_invoice_has_no_prefix(self) -> None:
        assert _builder().build_xml().startswith("<Invoice ")

    @_maybe_xfail
    def test_basic_components_use_cbc_prefix(self) -> None:
        s = _builder().build_xml()
        for tag in (
            "cbc:ID",
            "cbc:IssueDate",
            "cbc:InvoiceTypeCode",
            "cbc:DocumentCurrencyCode",
            "cbc:TaxAmount",
            "cbc:CityName",
            "cbc:RegistrationName",
            "cbc:Telephone",
            "cbc:Percent",
        ):
            assert tag in s, f"missing {tag}"

    @_maybe_xfail
    def test_aggregate_components_use_cac_prefix(self) -> None:
        s = _builder().build_xml()
        for tag in (
            "cac:AccountingSupplierParty",
            "cac:Party",
            "cac:PartyIdentification",
            "cac:PostalAddress",
            "cac:Country",
            "cac:TaxTotal",
            "cac:TaxSubtotal",
            "cac:LegalMonetaryTotal",
            "cac:InvoiceLine",
            "cac:AllowanceCharge",
            "cac:Item",
            "cac:Price",
        ):
            assert tag in s, f"missing {tag}"

    @_maybe_xfail
    def test_industry_classification_code_uses_cbc_not_cac(self) -> None:
        # IndustryClassificationCode is in CommonBasicComponents despite
        # living inside cac:Party (a CommonAggregateComponents wrapping).
        s = _builder().build_xml()
        assert '<cbc:IndustryClassificationCode name="Agriculture">01111' in s
        assert "cac:IndustryClassificationCode" not in s


# ---------------------------------------------------------------------------
# 4. Attribute ordering (C14N sorts alphabetically)
# ---------------------------------------------------------------------------


class TestC14nAttributeOrdering:
    @_maybe_xfail
    def test_invoice_type_code_attribute_comes_after_tag_before_text(self) -> None:
        s = _builder().build_xml()
        assert '<cbc:InvoiceTypeCode listVersionID="1.0">01</cbc:InvoiceTypeCode>' in s

    @_maybe_xfail
    def test_identification_code_attrs_alphabetical(self) -> None:
        # C14N sorts attributes alphabetically: listAgencyID before listID.
        s = _builder().build_xml()
        assert (
            "<cbc:IdentificationCode "
            'listAgencyID="6" listID="ISO3166-1">MYS</cbc:IdentificationCode>'
        ) in s
        # And the wrong order must NOT appear:
        assert 'listID="ISO3166-1" listAgencyID="6"' not in s

    @_maybe_xfail
    def test_tax_scheme_id_attrs_cover_schemeID_and_schemeAgencyID(self) -> None:
        s = _builder().build_xml()
        assert '<cbc:ID schemeAgencyID="6" schemeID="UN/ECE 5153">OTH</cbc:ID>' in s
        assert 'schemeID="UN/ECE 5153" schemeAgencyID="6"' not in s


# ---------------------------------------------------------------------------
# 5. Currency stamping + amount-as-array semantics (XML is singletons not arrays)
# ---------------------------------------------------------------------------


class TestXmlCurrencyStamping:
    @_maybe_xfail
    def test_amounts_carry_currencyID_attr_defaulting_to_document_currency(self) -> None:
        s = _builder().build_xml()
        assert '<cbc:TaxAmount currencyID="MYR">87.63</cbc:TaxAmount>' in s
        assert '<cbc:LineExtensionAmount currencyID="MYR">1436.50</cbc:LineExtensionAmount>' in s
        assert '<cbc:PriceAmount currencyID="MYR">17.00</cbc:PriceAmount>' in s
        assert '<cbc:Amount currencyID="MYR">100.00</cbc:Amount>' in s

    @_maybe_xfail
    def test_non_amount_basic_components_have_no_currencyID(self) -> None:
        # ID, IssueDate, IssueTime, etc. must NOT carry currencyID.
        s = _builder().build_xml()
        assert "currencyID" not in "<cbc:ID>" + "INV-0001" + "</cbc:ID>" or True  # soft check
        assert "<cbc:ID>INV-0001</cbc:ID>" in s
        assert "<cbc:IssueDate>2024-06-14</cbc:IssueDate>" in s


# ---------------------------------------------------------------------------
# 6. Repeatable elements (AddressLine, AllowanceCharge, etc.) emit multiple siblings
# ---------------------------------------------------------------------------


class TestXmlRepeatableElements:
    @_maybe_xfail
    def test_address_line_repeats_per_line_item(self) -> None:
        s = _builder().build_xml()
        # Sample has two AddressLine elements per postal address (x2 parties).
        assert s.count("<cac:AddressLine>") == 4
        assert s.count("<cbc:Line>Lot 66, Bangunan Merdeka</cbc:Line>") == 2
        assert s.count("<cbc:Line>Persiaran Jaya</cbc:Line>") == 2

    @_maybe_xfail
    def test_allowance_charge_repeats_in_invoice_line(self) -> None:
        s = _builder().build_xml()
        # Sample has two AllowanceCharge blocks in the InvoiceLine.
        assert s.count("<cac:AllowanceCharge>") == 2
        # First one: ChargeIndicator false, "Sample Description 2"
        assert "<cbc:ChargeIndicator>false</cbc:ChargeIndicator>" in s
        # Second: ChargeIndicator true, "Service charge"
        assert "<cbc:ChargeIndicator>true</cbc:ChargeIndicator>" in s


# ---------------------------------------------------------------------------
# 7. Unicode passthrough (screws not escaped)
# ---------------------------------------------------------------------------


class TestXmlUnicodePassthrough:
    @_maybe_xfail
    def test_chinese_description_emitted_as_raw_utf8(self) -> None:
        s = _builder().build_xml()
        # UBL XML默 allows raw UTF-8 in element text (storage is UTF-8,
        # c14n-1.1 does not re-encode to entities).
        assert "<cbc:Description>螺丝</cbc:Description>" in s
        # The wrong forms must NOT appear:
        assert "&#34746;&#19997;" not in s


# ---------------------------------------------------------------------------
# 8. Determinism + canonicalisation
# ---------------------------------------------------------------------------


class TestXmlDeterminism:
    @_maybe_xfail
    def test_two_runs_produce_identical_string(self) -> None:
        a = _builder().build_xml()
        b = _builder().build_xml()
        assert a == b

    @_maybe_xfail
    def test_canonicalisation_idempotent(self) -> None:
        # Re-canonicalising the output should produce the same bytes — this
        # proves the output is already in c14n-1.0 inclusive form (Phase 4
        # will rely on this invariant for the signature digest computation).
        # NB: the c14n mode MUST match the builder's (exclusive=False) — exclusive
        # c14n pulls the xmlns declarations down to the first-usage element rather
        # than keeping them on root, which is a strictly different canonical form
        # and produces naturally-different bytes (not an idempotency failure).
        out = _builder().build_xml()
        from lxml import etree

        reparsed = etree.fromstring(out.encode("utf-8"))
        re_c14n = etree.tostring(
            reparsed,
            method="c14n",
            exclusive=False,
            with_comments=False,
        ).decode("utf-8")
        assert re_c14n == out


# ---------------------------------------------------------------------------
# 9. The big one — byte-for-byte parity with the golden fixture
# ---------------------------------------------------------------------------


class TestReferenceByteParity:
    @_maybe_xfail
    def test_byte_for_byte_matches_reference_xml_output(self) -> None:
        """The single test that anchors Phase 3c-XML correctness.

        ``tests/fixtures/golden_invoice_unsigned.xml`` is the exact output of
        the reference ``XmlDocumentBuilder::build()``
        on the invoice mirrored into
        ``_sample_invoice()``. The fixture was md5-sum-diffed against the reference
        output at fixture-population time and committed.
        """
        actual = _builder().build_xml()
        golden = _golden_xml()
        if actual != golden:
            # Diagnostics: walk to the first divergent character.
            n = min(len(actual), len(golden))
            for i in range(n):
                if actual[i] != golden[i]:
                    raise AssertionError(
                        "envelope XML drifted from the reference.\n"
                        f"  diff at index {i}:\n"
                        f"  actual[{i}]: ...{actual[max(0, i - 60) : i + 60]!r}\n"
                        f"  golden[{i}]: ...{golden[max(0, i - 60) : i + 60]!r}"
                    )
            longer = "actual" if len(actual) > len(golden) else "golden"
            raise AssertionError(
                f"strings diverge in length; {longer} longer "
                f"(actual={len(actual)}, golden={len(golden)})"
            )
